#  Author: Mathias Kluba

version: '2.1'
services:
  db4all:
    image: grozeille/db4all:1.0-SNAPSHOT
    ports:
      - "9800:9800"
    links:
      - "hbase:hbase"
      - "solrcloud:solrcloud"
  hbase:
    image: harisekhon/hbase:1.2
    hostname: hbase
    ports:
      - 2181:2181
      - 8080:8080
      - 8085:8085
      - 9090:9090
      - 9095:9095
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    #volumes:
    #  - /tmp/hbase-root/:/tmp/hbase-root/
  solrcloud:
    # using my own Docker images now as official solr doesn't have builds < 5
    image: harisekhon/solrcloud:7.1
    hostname: solrcloud
    ports:
      - 8983:8983
      - 8984:8984
      - 9983:9983
    #volumes:
    #  - /tmp/solr-cloud/:/solr/example/cloud/
