#  Author: Mathias Kluba

version: '2.0'
services:
  db4all:
    image: grozeille/db4all:1.0-SNAPSHOT
    ports:
      - "9800:9800"
    links:
      - "hbase:hbase"
      - "solrcloud:solrcloud"
    labels:
      io.rancher.container.pull_image: always
    #environment:
    #  - GRAYLOG2_HOST=graylog
    #  - GRAYLOG2_PORT=12201
  hbase:
    image: grozeille/hbase:latest
    hostname: hbase
    ports:
      - 2181:2181
      - 8080:8080
      - 8085:8085
      - 9090:9090
      - 9095:9095
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - /tmp/hbase-root
    #environment:
    #  - GRAYLOG2_HOST=graylog
    #  - GRAYLOG2_PORT=12201
  solrcloud:
    # using my own Docker images now as official solr doesn't have builds < 5
    image: grozeille/solrcloud:latest
    hostname: solrcloud
    ports:
      - 8983:8983
      - 8984:8984
      - 9983:9983
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - /solr/example/cloud
    #environment:
    #  - GRAYLOG2_HOST=graylog
    #  - GRAYLOG2_PORT=12201
