server:
  port: 9900

logging.level.org.hibernate.SQL: debug
logging.level.org.apache.hadoop.yarn.util.RackResolver: warn


spring:
  jackson.serialization.write_dates_as_timestamps: false
  http:
    multipart:
      enabled: true
      max-file-size: 500Mb
      max-request-size: 550Mb

db4all:
  adminToken: e5e68d89adc641b2946b6c770c4fd7c7e23f278e
  solr:
    zkUrl: localhost:9983
  hbase:
    zkUrl: localhost:2181


security:
  enabled: false
  oauth2:
    client:
      clientId:
      clientSecret:
      accessTokenUri:
      userAuthorizationUri:
      tokenName:
      authenticationScheme:
      clientAuthenticationScheme:
    resource:
      userInfoUri: