server:
  port: 9800

logging.level.org.hibernate.SQL: debug
logging.level.org.apache.hadoop.yarn.util.RackResolver: warn


spring:
  jackson.serialization.write_dates_as_timestamps: false
  h2.console.enabled: true
  jpa:
    database: H2
    hibernate:
      ddl-auto: none
  datasource:
    primary:
        url: jdbc:h2:./target/database/db
        username: sa
        password:
        driver-class-name: org.h2.Driver
  http:
    multipart:
        enabled: true
        max-file-size: 500Mb
        max-request-size: 550Mb

db4all:
  adminToken: e5e68d89adc641b2946b6c770c4fd7c7e23f278e
  solr:
    embedded: true
    home: ./target/solr-home
    zkUrl:


security:
  enabled: false
  oauth2:
    client:
      clientId:
      clientSecret:
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
